name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: codecup-codeday/chal-lfi/chal-lfi
        registry: docker.pkg.github.com
        tag_names: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        default_branch: main
